const fs = require('fs')
const util = require('util')

const table = require('./aarch64_syscalls')
const syscalls = table.syscalls;

console.log("<html>")
console.log("<head>")
console.log("  <meta charset=\"utf-8\">")
console.log("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">")
console.log("  <link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css\" integrity=\"sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm\" crossorigin=\"anonymous\">")
console.log("  <title>Linux System Call Table - aarch64</title>")
console.log("</head>")
console.log("<body style=\"background-color: #212529\">")
console.log("  <h1 class=\"text-white\">Linux System Call Table - aarch64</h1>")
console.log("  <p class=\"text-white\">Generated from Linux kernel %s</p>", table.version)
console.log("  <p class=\"text-white\">Project on <a class=\"badge badge-secondary\" href=\"https://github.com/Thog/syscalls-table-aarch64\">GitHub</a></p>")
console.log("  <p class=\"text-white\">Hosted on <a class=\"badge badge-secondary\" href=\"https://pages.github.com/\">GitHub Pages</a></p>")
console.log("  <table class=\"table table-dark table-hover\">")
console.log("    <thead>")
console.log("      <tr>")
console.log("        <th scope=\"col\">#</th>")
console.log("        <th scope=\"col\">Name</th>")
console.log("        <th scope=\"col\" colspan=\"7\">Registers</th>")
console.log("        <th scope=\"col\">Definition</th>")
console.log("      </tr>")
console.log("      <tr>")
console.log("        <th scope=\"col\"></th>")
console.log("        <th scope=\"col\"></th>")
console.log("        <th scope=\"col\">x7</th>")
console.log("        <th scope=\"col\">x0</th>")
console.log("        <th scope=\"col\">x1</th>")
console.log("        <th scope=\"col\">x2</th>")
console.log("        <th scope=\"col\">x3</th>")
console.log("        <th scope=\"col\">x4</th>")
console.log("        <th scope=\"col\">x5</th>")
console.log("        <th scope=\"col\"></th>")
console.log("      </tr>")
console.log("    </thead>")
console.log("    <tbody>")
for (syscall of syscalls)
{
    console.log("      <tr>")
    console.log("        <th scope=\"col\">%d</th>", syscall.num)
    console.log("        <td><a class=\"badge badge-dark\" href=\"http://man7.org/linux/man-pages/man2/%s.2.html\">%s</a></td>", syscall.name, syscall.name)
    console.log("        <td>0x%s</td>", syscall.syscall_id.toString('16').toUpperCase())
    console.log("        <td>%s</td>", syscall.args[0] ? syscall.args[0] : '' )
    console.log("        <td>%s</td>", syscall.args[1] ? syscall.args[1] : '' )
    console.log("        <td>%s</td>", syscall.args[2] ? syscall.args[2] : '' )
    console.log("        <td>%s</td>", syscall.args[3] ? syscall.args[3] : '' )
    console.log("        <td>%s</td>", syscall.args[4] ? syscall.args[4] : '' )
    console.log("        <td>%s</td>", syscall.args[5] ? syscall.args[5] : '' )
    console.log("        <td><a class=\"badge badge-dark\" href=\"http://elixir.free-electrons.com/linux/v%s/source/%s#L%d\">%s:%d</a></td>",  table.version, syscall.source.file, syscall.source.line, syscall.source.file, syscall.source.line)
    console.log("      </tr>")
}
console.log("    </tbody>")
console.log("  </table>")
console.log("</body>")
console.log("</html>")
